name: Release Please

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
    outputs:
      binary_release_created: ${{ steps.release.outputs['crates/nixpkgs-track--release_created'] == 'true' }}
      library_release_created: ${{ steps.release.outputs['crates/nixpkgs-track_lib--release_created'] == 'true' }}

  release-binary:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.binary_release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Publish
        run: cargo publish --verbose --locked --no-verify --package nixpkgs-track
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}

  release-library:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.binary_release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v2

      - name: Publish
        run: cargo publish --verbose --locked --no-verify --package nixpkgs-track_lib
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_TOKEN }}
